builders:
  testBuilder:
    import: "package:flutter_generate_assets/builder.dart"
    builder_factories: ["resourceFileBuilder"]
    build_extensions: {".png":   [".png.dart"],".jpg":   [".jpg.dart"],".jpeg":  [".jpe.dart"],".gif":   [".gif.dart"],".webp":  [".web.dart"],".bmp":   [".bmp.dart"],".wbmp":  [".wbm.dart"],".yaml":  [".yam.dart"],".lock":  [".loc.dart"],}
    build_to: source
    auto_apply: root_package

# targets:
#   $default:
#     sources:
#       - my_custom_sources/**
#       - lib/**
#       - web/**
#       # Note that it is important to include these in the default target.
#       - pubspec.*    