name: flutter_generate_assets
email: danhang152@gmail.com
homepage: https://github.com/cherrybiu/flutter_generate_assets
version: 0.1.0
description: Automatically generate a resource file by scanning pubspec.yaml to correspond to the flutter's asset, imitation R file short name.

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  args: ^1.5.2
  io: ^0.3.3
  path: ^1.6.4
  yaml: ^2.1.16
  glob: ^1.2.0
  dart_style: ^1.3.8

executables:
  sgen: resource_generator
