name: flutter_generate_assets
email: danhang152@gmail.com
homepage: https://github.com/cherrybiu/flutter_generate_assets
version: 0.2.1
description: To satisfy our team's needs, I changed something based on previous author's repository(flutter_asset_generator).

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.1
  io: ^1.0.0
  path: ^1.8.0
  yaml: ^3.1.0
  glob: ^2.0.1
  dart_style: ^2.0.1

executables:
  sgen: resource_generator
